-- MySQL Script generated by MySQL Workbench
-- Wed Jun 12 10:31:23 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema GameBD
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema GameBD
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `GameBD` DEFAULT CHARACTER SET utf8 ;
USE `GameBD` ;

-- -----------------------------------------------------
-- Table `GameBD`.`player`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GameBD`.`player` (
  `idplayer` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `vida` FLOAT NULL,
  `dano` FLOAT NULL,
  `Class` INT NULL,
  `salve` INT NULL,
  PRIMARY KEY (`idplayer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GameBD`.`posicao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GameBD`.`posicao` (
  `mapa` VARCHAR(45) NULL,
  `x` FLOAT NULL,
  `y` INT NULL,
  `player_idplayer` INT NOT NULL,
  PRIMARY KEY (`player_idplayer`),
  CONSTRAINT `fk_posicao_player`
    FOREIGN KEY (`player_idplayer`)
    REFERENCES `GameBD`.`player` (`idplayer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
